### ISSUE TITLE
Hidden Malicious Code In This Script

### ISSUE THREAD

**Issue by ArkSeyonet** [Bluscream/LunaPark-FiveM#1]
Hello, I am one of the managers of the ESX Framework. We have been searching through forks of ESX code, to find malicious content.

![image](https://user-images.githubusercontent.com/31637812/122565759-753c4080-d00c-11eb-857b-b5a8ef5d1a00.png)

You should remove this code, as the person that originally created this script included malicious code in it. (Although this code has been removed from pastebin, you should know that it was malicious.)

**Comment by Bluscream** [comment]
Where is the file you're refering to?
